//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodSale()
        {
            this.Cart = new HashSet<Cart>();
            this.Cart1 = new HashSet<Cart>();
            this.Cart2 = new HashSet<Cart>();
        }
    
        public int FoodSaleID { get; set; }
        public Nullable<int> UserRecipeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> Stocks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart2 { get; set; }
        public virtual UserRecipe UserRecipe { get; set; }
    }
}
