//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoodBiteEntities : DbContext
    {
        public MoodBiteEntities()
            : base("name=MoodBiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCreationLog> AccountCreationLog { get; set; }
        public virtual DbSet<Allergy> Allergy { get; set; }
        public virtual DbSet<BuyPremiumTransaction> BuyPremiumTransaction { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<FoodCategory> FoodCategory { get; set; }
        public virtual DbSet<FoodSale> FoodSale { get; set; }
        public virtual DbSet<Intolerance> Intolerance { get; set; }
        public virtual DbSet<Mood> Mood { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<OrderMaster> OrderMaster { get; set; }
        public virtual DbSet<OrderPayment> OrderPayment { get; set; }
        public virtual DbSet<Premium> Premium { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<RecipeAllergy> RecipeAllergy { get; set; }
        public virtual DbSet<RecipeImage> RecipeImage { get; set; }
        public virtual DbSet<RecipeIngredient> RecipeIngredient { get; set; }
        public virtual DbSet<RecipeIntolerance> RecipeIntolerance { get; set; }
        public virtual DbSet<RecipeRating> RecipeRating { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Testimonials> Testimonials { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPremium> UserPremium { get; set; }
        public virtual DbSet<UserRecipe> UserRecipe { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UsersFavoriteRecipes> UsersFavoriteRecipes { get; set; }
        public virtual DbSet<vw_AllRecipeDetailsWithFoodCategoryName> vw_AllRecipeDetailsWithFoodCategoryName { get; set; }
        public virtual DbSet<vw_AllUserColWithRecipeID> vw_AllUserColWithRecipeID { get; set; }
        public virtual DbSet<vw_CartView> vw_CartView { get; set; }
        public virtual DbSet<vw_CheckOutView> vw_CheckOutView { get; set; }
        public virtual DbSet<vw_CoverImageOfRecipes> vw_CoverImageOfRecipes { get; set; }
        public virtual DbSet<vw_FilterAllergy> vw_FilterAllergy { get; set; }
        public virtual DbSet<vw_FoodSaleView> vw_FoodSaleView { get; set; }
        public virtual DbSet<vw_ForOrderPaymentInsertionView> vw_ForOrderPaymentInsertionView { get; set; }
        public virtual DbSet<vw_ManageSubscriptions> vw_ManageSubscriptions { get; set; }
        public virtual DbSet<vw_ManageUploads> vw_ManageUploads { get; set; }
        public virtual DbSet<vw_ManageUsers> vw_ManageUsers { get; set; }
        public virtual DbSet<vw_OrderDetailView> vw_OrderDetailView { get; set; }
        public virtual DbSet<vw_RecipeDetailsWithoutIngredients> vw_RecipeDetailsWithoutIngredients { get; set; }
        public virtual DbSet<vw_RecipeDetailsWithoutIngredientsWithRating> vw_RecipeDetailsWithoutIngredientsWithRating { get; set; }
        public virtual DbSet<vw_recipeUploadersNameWithRating> vw_recipeUploadersNameWithRating { get; set; }
        public virtual DbSet<vw_RecipeWithMoodName> vw_RecipeWithMoodName { get; set; }
        public virtual DbSet<vw_RecommendedRecipeForMood> vw_RecommendedRecipeForMood { get; set; }
        public virtual DbSet<vw_RoleView> vw_RoleView { get; set; }
        public virtual DbSet<vw_UploaderDetailsForReadMorePage> vw_UploaderDetailsForReadMorePage { get; set; }
        public virtual DbSet<vw_UserDetailsWithRole> vw_UserDetailsWithRole { get; set; }
        public virtual DbSet<vw_UsersUploadCounts> vw_UsersUploadCounts { get; set; }
        public virtual DbSet<vw_UserRecipeView> vw_UserRecipeView { get; set; }
    }
}
