//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int OrderPaymentID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
