//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class RecipeImage
    {
        public int RecipeImageID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageURL { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Recipe Recipe { get; set; }
    }
}
