//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int RecipeIngredientID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string IngredientName { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
