//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CheckOutView
    {
        public int userID { get; set; }
        public int RecipeID { get; set; }
        public int FoodSaleID { get; set; }
        public int CartID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public byte[] ImageURL { get; set; }
    }
}
