//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FoodSaleView
    {
        public int FoodSaleID { get; set; }
        public int userID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserRecipeID { get; set; }
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
