//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_IncomingOrderView
    {
        public int OrderDetailID { get; set; }
        public int PO_ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> EstimatedArrivalTime { get; set; }
        public Nullable<int> DeliveryFee { get; set; }
        public Nullable<int> FoodForSaleID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Shop_Address { get; set; }
        public int RecipeID { get; set; }
        public Nullable<int> MoodID { get; set; }
        public Nullable<int> FoodCategoryID { get; set; }
        public string RecipeName { get; set; }
        public string RecipeDescription { get; set; }
        public Nullable<int> IngredientsCount { get; set; }
        public string CookingInstruction { get; set; }
        public Nullable<System.TimeSpan> PreparationTime { get; set; }
        public Nullable<System.TimeSpan> CookingDuration { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
    }
}
