//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ManageUploads
    {
        public int ID { get; set; }
        public string RecipeName { get; set; }
        public string Uploaded_by { get; set; }
        public Nullable<System.DateTime> Date_uploaded { get; set; }
        public Nullable<System.DateTime> Date_approved { get; set; }
        public string Approved_by { get; set; }
        public string Status { get; set; }
    }
}
