//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodBite
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RecommendedRecipeForMood
    {
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public string FoodCategoryName { get; set; }
        public string MoodName { get; set; }
        public int userID { get; set; }
        public string Uploaded_by { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string Approved_by { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public int RecipeImageID { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageURL { get; set; }
    }
}
